### ISSUE TITLE
Block VPN connections

### ISSUE THREAD

**Issue by linsaftw** [arkflame/FlameCord#212]
Method 1: Stay on logging in... screen until VPN finishes checking. (Normal connections will take a little longer)
Method 2: Let the bot in and then kick him when VPN is checked. (Bots will deal more damage)

**Comment by Sn0wyYTx** [comment]
1

**Comment by pabloalba16** [comment]
1

**Comment by MachineBreaker** [comment]
Make it configurable to switch between 1 and 2

**Comment by R1C4RD0x** [comment]
1

**Comment by UnDeadlyDev** [comment]
1

**Comment by fu3i0n** [comment]
1

**Comment by iChocoMC** [comment]
Make it configurable to switch between 1 and 2.
