### ISSUE TITLE
Ability to add custom proxy list

### ISSUE THREAD

**Issue by andriycraft** [arkflame/FlameCord#215]
At the moment there are 5 hardcoded ones:

https://github.com/arkflame/FlameCord/commit/943e18df7a2b285071c32831317c76a14629a8fd#diff-313caea1c63dd8e1c5c0ee42d3ed4d85b0b7c50cabc1a4c415d35a1c242b829cR1122

**Comment by linsaftw** [comment]
Awesome idea

**Comment by linsaftw** [comment]
Done
